import eventOrg from "./../assets/event-org.png";
import hitsIcon from "./../assets/hits-icon.svg";
import wecIcon from "./../assets/wec-icon.svg";
import rockingIcon from "./../assets/rocking-icon.svg";
import marsIcon from "./../assets/mars-icon.svg";

export const upcomingEventsData = [
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        regoCloses: "12.06.22",
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        regoCloses: "05.15.22",
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        regoCloses: "11.13.22",
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        regoCloses: "07.23.22",
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        regoCloses: "01.30.22",
    },
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        regoCloses: "12.06.22",
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        regoCloses: "05.15.22",
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        regoCloses: "11.13.22",
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        regoCloses: "07.23.22",
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        regoCloses: "01.30.22",
    },
];

export const competitionResultsData = [
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        placement: 1,
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        placement: 4,
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        placement: 1,
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        placement: 3,
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        placement: 2,
    },
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        placement: 1,
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        placement: 4,
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        placement: 1,
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        placement: 3,
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        placement: 2,
    },
];

export const eventHistoryData = [
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        attendees: "12",
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        attendees: "32",
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        attendees: "2090",
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        attendees: "12",
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        attendees: "21",
    },
    {
        icon: eventOrg,
        name: "USEF Championship Dressage IV",
        discipline: "Dressage",
        eventType: "Licensed",
        location: "Florida",
        startDate: "12.06.22",
        attendees: "5",
    },
    {
        icon: hitsIcon,
        name: "HITS Fall Series",
        discipline: "Eventing",
        eventType: "Schooling",
        location: "Virginia",
        startDate: "05.15.22",
        attendees: "230",
    },
    {
        icon: wecIcon,
        name: "PBIEC winter festival X1",
        discipline: "Hunter Jumper",
        eventType: "Schooling",
        location: "Maryland",
        startDate: "11.13.22",
        attendees: "120",
    },
    {
        icon: rockingIcon,
        name: "Rocking Horse Spring Trials",
        discipline: "Eventing",
        eventType: "Clinc",
        location: "Georgia",
        startDate: "07.23.22",
        attendees: "12",
    },
    {
        icon: marsIcon,
        name: "MARS Summer Camp Event",
        discipline: "Equitation",
        eventType: "Licensed",
        location: "California",
        startDate: "01.30.22",
        attendees: "102",
    },
];

export const stateNames = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];
